# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '8.0'

def pods_files
    pod 'XBButton'
    pod 'XBTimer'
end

target 'XBUniversalCell' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pods_files
  # Pods for XBUniversalCell

  target 'XBUniversalCellTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XBUniversalCellUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
